################

# CORRELATION ------------------------------------------------------------------

cor.names <- c("spearman", "pearson")

xframe <- xframe[complete.cases(xframe),]


# All data subsets
data.gdp <- xframe[,c(waste.generated.by.list, "GDP")]
data.pop <- xframe[,c(waste.generated.by.list, "Total Population")]
data.capita <- xframe[,c(waste.generated.by.list, "Per Capita GDP")]

# Correlation matrix
for (i in cor.names){
  cor.gdp <- cor(data.gdp, use = "complete.obs", method = i)
  cor.pop <- cor(data.pop, use = "complete.obs", method = i)
  cor.capita <- cor(data.capita, use = "complete.obs", method = i)
  
  waste.cor <- do.call("cbind", list(cor.gdp[-9,9], cor.pop[-9,9], cor.capita[-9,9]))
  waste.cor <- data.frame(waste.cor)
  names(waste.cor) <- c("gdp", "pop", "gdp per capital")
  assign(paste0("waste.cor.", i), waste.cor)
}


# CORRELATION 2 ----------------------------------------------------------------

xframe2 <- xframe[,c("CountryName", "Year", waste.generated.by.list)]
xframe2 <- xframe2[complete.cases(xframe2),]

for (i in cor.names) {
 assign(paste0("waste.cor.all.", i), cor(xframe2[,waste.generated.by.list], use = "complete.obs", method = i))
}


# CORRELATION 3 ----------------------------------------------------------------

# Correlation with "Waste Generated by Sector"
xframe <- alldata[,c("CountryName", "Year", "Waste Generated by Sector")]
xframe <- xframe[complete.cases(xframe),]

# Merge all who data and obese data
xframe <- merge(xframe, regressors)

# All data subsets
data.gdp <- xframe[,c("Waste Generated by Sector", "GDP")]
data.pop <- xframe[,c("Waste Generated by Sector", "Total Population")]
data.capita <- xframe[,c("Waste Generated by Sector", "Per Capita GDP")]

# Correlation matrix
for (i in cor.names){
  cor.gdp <- cor(data.gdp, use = "complete.obs", method = i)
  cor.pop <- cor(data.pop, use = "complete.obs", method = i)
  cor.capita <- cor(data.capita, use = "complete.obs", method = i)
  
  waste.cor <- do.call("cbind", list(cor.gdp[-2,2], cor.pop[-2,2], cor.capita[-2,2]))
  waste.cor <- data.frame(waste.cor)
  names(waste.cor) <- c("gdp", "pop", "gdp per capital")
  row.names(waste.cor) <- "Waste Generated by Sector"
  assign(paste0("total.waste.cor.", i), waste.cor)
}

